project_id = "gzeovhwoouoxfenaxsss"

[functions.calendar-ics]
verify_jwt = false

[functions.weekly-backup]
verify_jwt = false


[functions.seed-users]
verify_jwt = false

[functions.public-case-status]
verify_jwt = false
